[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_anchor_nft = "GmCTiB5hb9MqLJnBmzXFzc4NDziAejG8Nhf6RAiLzowG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/m1/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
